<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SysPro.Ingestion</RootNamespace>
        <UserSecretsId>2e2fe65f-f292-4fea-bf54-cf79e1ae0652</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SysPro.Application\SysPro.Application.csproj" />
      <ProjectReference Include="..\SysPro.DB\SysPro.DB.csproj" />
      <ProjectReference Include="..\SysPro.Domain\SysPro.Domain.csproj" />
    </ItemGroup>

</Project>
